# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
puts "Seeding..."

User.create(username: "test")

# Genres
scifi = Genre.create(name: "Sci-Fi")
suspense = Genre.create(name: "Suspense")
action = Genre.create(name: "Action Adventure")
fantasy = Genre.create(name: "Fantasy")
paranormal = Genre.create(name: "Paranormal")
mystery = Genre.create(name: "Mystery")
horror = Genre.create(name: "Horror")
romance = Genre.create(name: "Romance")
other = Genre.create(name: "General/Other")

# Authors
alan = Author.create(name: "Alan Turing")
ada = Author.create(name: "Ada Lovelace")
jk = Author.create(name: "JK Rowling")
george = Author.create(name: "George RR Martin")
james = Author.create(name: "James Joyce")
bill = Author.create(name: "William Faulkner")


# def story_params
#   params.permit(:id, :genre_id, :title)

# Stories
## scifi
spaceship = Story.create(genre_id: scifi[:id], title: "The Scary Spaceship")
new_worlds = Story.create(genre_id: scifi[:id], title: "New Worlds")
robots = Story.create(genre_id: scifi[:id], title: "The Helpful Robot")

## suspense
mind_eraser = Story.create(genre_id: suspense[:id], title: "Mind Eraser")
lottery = Story.create(genre_id: suspense[:id], title: "Forbidden Lottery")
inheritance = Story.create(genre_id: suspense[:id], title: "Inheritance")

## action
takeover = Story.create(genre_id: action[:id], title: "Hostile Takeover")
escape = Story.create(genre_id: action[:id], title: "Escape from Sword Island")
battle = Story.create(genre_id: action[:id], title: "Battle for Evergard")

## fantasy
crystal = Story.create(genre_id: fantasy[:id], title: "The Forever Crystal")
dragon = Story.create(genre_id: fantasy[:id], title: "Dragon Chaser")
mage = Story.create(genre_id: fantasy[:id], title: "The Drunken Mage")

## paranormal
spooky = Story.create(genre_id: paranormal[:id], title: "The Spooky Campground")
possession = Story.create(genre_id: paranormal[:id], title: "Johnny's Possession")
altered = Story.create(genre_id: paranormal[:id], title: "Altered State")

## mystery
hidden = Story.create(genre_id: mystery[:id], title: "The Hidden Letters")
bargain = Story.create(genre_id: mystery[:id], title: "Bargain for Truth")
choices = Story.create(genre_id: mystery[:id], title: "Wrong Choices")

## horror
blood = Story.create(genre_id: horror[:id], title: "Blood Stained Door")
creepy = Story.create(genre_id: horror[:id], title: "Creepy Dollhouse")
demon = Story.create(genre_id: horror[:id], title: "Demon Lawyer")

## romance
forbidden = Story.create(genre_id: romance[:id], title: "Forbidden Love")
timing = Story.create(genre_id: romance[:id], title: "Bad Timing")
gentleman = Story.create(genre_id: romance[:id], title: "Secret Gentleman")

## other
lilac = Story.create(genre_id: other[:id], title: "Lilac Bushes")
how_to = Story.create(genre_id: other[:id], title: "How to Plan a Roadtrip")
family = Story.create(genre_id: other[:id], title: "The Silly Family")


puts "Stories created, now on to Paragraphs..."

# Paragraphs

puts "Creating paragraphs..."


# def paragraph_params
#   params.permit(:id, :author_id, :story_id, :rich_text_str)
## scifi
Paragraph.create(author_id: alan[:id], story_id: spaceship[:id], rich_text_str: "<p>The scary spaceship that flies to the edge of the galaxy and runs into another species . The ship was a small, black box. It's exterior looked like a large, metal box with a single, large window that was open. Inside were the bodies of a dozen people who had died in battle.</p>")
Paragraph.create(author_id: ada[:id], story_id: spaceship[:id], rich_text_str: "<p>This is where the ship came from and where it was going. Palskos was a world of peace and tranquility. No one had ever heard of a ship crashing into a peaceful world. If there was ever a time for war, this was it.</p>")
Paragraph.create(author_id: jk[:id], story_id: spaceship[:id], rich_text_str: "<p>But one thing the crew of the spaceship didn't take into account was the anti-gravity of the planet below. As soon as they began their descent into the atmosphere of Palskos, they started to slow down. The ship started shaking like it was going to be torn apart.</p>")

Paragraph.create(author_id: george[:id], story_id: new_worlds[:id], rich_text_str: "<p>I had never been to a funeral before, as at the age of six my parents thought death was too difficult a topic for me to grasp. I've heard of them though, dark, long trails of cloth glided along the bodies of weeping women who covered their red eyes with black netted hats. Then, they have a big party; I know this for myself because I stayed home when my grandpapi died when I was four. I was told to stay in my room, but the sound of the steelpan floated through my window. My granpapi was a pan teacher you see, and from then, I associated death with black clothes and party. What was sad about a party?</p>")
Paragraph.create(author_id: james[:id], story_id: new_worlds[:id], rich_text_str: "<p>It was in the middle of the Mathematics class. Mrs Taylor our teacher suddenly collapsed and sprawled unconscious on the floor. It was terrifying. The chalk she held in her hand scraped against the chalkboard making her incorrectly tell us that 2+3=1. We sat there. None of us, being the naive kindergarteners we were, understood this dire situation. Mrs Taylor's pretty hair lay knotted around her pretty face and blood seeped through her pretty pants.</p>")
Paragraph.create(author_id: bill[:id], story_id: new_worlds[:id], rich_text_str: "<p>'Mrs Taylor! Mrs Taylor!' we finally cried. She did not move. She never slept during our scheduled naptime, so why would she sleep now. The blood continued to run, as Corey, the oldest boy in our class ran to his mother, the Principal. Madam Collins ran into our class, but stopped abruptly at the door. 'Oh dear me,' she whispered. She pulled her cell phone from her pocket and called the police. After, she called Mr Taylor.</p>")

Paragraph.create(author_id: alan[:id], story_id: robots[:id], rich_text_str: "<p>Something happened in the lab the other night. I'm not certain what but it was something. I powered up the device, and there she…I…the other I…was. It was a possibility I hadn't considered. By opening a door into a parallel universe, I opened the door to myself in that same universe.</p>")
Paragraph.create(author_id: jk[:id], story_id: robots[:id], rich_text_str: "<p>Some clarification first. My name is Samuel Worth, I am a thirty-four-year-old physicist that likes doing stupid experiments in my garage. I go by Sam. Her name is Samantha Worth, a thirty-four-year-old physicist that likes doing stupid experiments in her garage…she goes by Sam.</p>")
Paragraph.create(author_id: james[:id], story_id: robots[:id], rich_text_str: "<p>One difference at our conception, or possibly even sooner. We look too alike to have a wildly different selection of genes from our mother and father. We knew, in an instant. Until the age of twelve, we looked identical.</p>")

# suspense
Paragraph.create(author_id: ada[:id], story_id: mind_eraser[:id], rich_text_str: "<p>September in Chicago, 1972. I was sitting alone in a stuffy train compartment and peering out of the window. The evening landscape outside was monotonous: at least nothing new had happened there since I departed from Rockwell station. I was heading to Chicago from the small town of Rockwell, where I had lived for almost 30 years. All I carried with me was a rusty suitcase packed with my stuff, and a blank lottery ticket which I bought on a station before boarding the train-not that I believed in luck. It was a momentary intention, and to tell the truth, I was a bit ashamed to buy that ticket: it felt like I was desperate and hoped to attain the attainable.</p>")
Paragraph.create(author_id: george[:id], story_id: mind_eraser[:id], rich_text_str: "<p>I looked at my translucent reflection in the window glass. A middle-aged white man with a thin nose and deep-set, prickly eyes; a man seeking for a new life and new opportunities, someone who had left his past behind but didnt yet have a clear idea of his future. What I knew was that I was starting over: nothing else mattered.</p>")
Paragraph.create(author_id: bill[:id], story_id: mind_eraser[:id], rich_text_str: "<p>In half an hour, the train made a short stop at some small no-name station, and I had an odd feeling come over me; I spent a couple of minutes trying to figure out what it was before it dawned on me. I had traveled in this direction for the last 10 years, but trains never stopped on their way to Chicago or from it. Actually, I couldnt remember that I had ever seen that station-and I knew the landscape outside in detail. The reason why I had to go to Chicago was easy to explain-I had to bring my manuscripts to the publishing house, in person. Dont ask me the details.</p>")

Paragraph.create(author_id: bill[:id], story_id: lottery[:id], rich_text_str: "<p>When the boat went over, tilting on one side as the welter of human bodies moved as one to see the distant coastline twinkling like a line in the constellations, the glee of sighting land in the murky gleam of dawn was crushed by the crank of metal lifting and a great swoosh of water rushing away from the hull. For a moment Adejo was in the sky, as if looking out from a tall building over the ocean, but then he was falling as quickly as he had risen, tossed with hundreds of others in the collective splay of arms and legs as their once condensed bodies were suddenly being dispersed in a spray of screams.</p>")
Paragraph.create(author_id: james[:id], story_id: lottery[:id], rich_text_str: "<p>The crest of a wave had risen up to meet Adejo as he struck it, landing on his back atop the watery peak. The ocean opened up for him as it did for others all around him, perfectly sized perforations for the bodies that peppered the surface. Beneath the water line Adejo saw a woman with a shawl around her neck and her single exposed breast glowing in the gloom like a beacon. Others thrashed their limbs in various failed combinations in the hope they might trick their bodies into the virgin act of swimming, yet one boy kicked to the surface with an ease that suggested he had been born in the depths, while all around him others started to sink helplessly, their tightly sealed mouths now giving way to gurgling screams, a flush of bubbles the last thing Adejo ever saw of them before a hand grabbed him.</p>")
Paragraph.create(author_id: bill[:id], story_id: lottery[:id], rich_text_str: "<p>The air met his lungs on the surface, assaulting them with fresh life while the man who had lifted him there was already diving again. Adejo never saw him rise; losing sight of the spot where he had descended; the constant churn of waves erasing it as soon as it had been created.</p>")

Paragraph.create(author_id: james[:id], story_id: inheritance[:id], rich_text_str: "<p>The other day, I was sitting on a veranda and wrote some text for a website. A big mug of green tea stood on a table nearby, and my old laptop quietly played songs from the good old days, something directly from the epoch of Kerouac, Bradbury, and rainy Chicago nights. In the evening, my wife and I invited our friends to have dinner at our place, so the day promised to be pleasant. It was a special pleasure to have such a peaceful day after three weeks of hiking, snowboarding, and going crazy.</p>")
Paragraph.create(author_id: george[:id], story_id: inheritance[:id], rich_text_str: "<p>'Hi dad!' My son burst onto the veranda, tore off his backpack, and fell into the armchair, breathing heavily; after a while, he leaped onto his feet and headed towards the kitchen.
'Want some orange juice, graybeard?' he yelled to me much louder than needed. 'No, just bring me some chips!' I shouted back.</p>")
Paragraph.create(author_id: james[:id], story_id: inheritance[:id], rich_text_str: "<p>Once, when I misheard what he said to me three times in a row, he joked that I had become too old and probably started to hear worse. Since that day, yelling at me has become a kind of family joke.</p>")

## action
Paragraph.create(author_id: george[:id], story_id: takeover[:id], rich_text_str: "<p>I like to look through holes. The gaps in a steel mesh above the conductors door on a tram. The space between escalator stairs as they climb. The spaces between leaves on a tree, especially on a windy day.</p>")
Paragraph.create(author_id: jk[:id], story_id: takeover[:id], rich_text_str: "<p>Some people are into getting close to perfection as possible, cleaning and repairing walls and other surroundings excessively. A flaw, such as a hole, can give depth. I was riding a tram into the center of Kyiv, and there was this section of paint that had collapsed, leaving a purple blotch-like metal beneath the usual yellow paint. It was like a vein cut into, yet it didnt bleed, exposed to passengers without its consent.</p>")
Paragraph.create(author_id: george[:id], story_id: takeover[:id], rich_text_str: "<p>I dont tell people about the holes I see and the fascination I have with them. They would comment about me needing to take a certain drug or they will think about the psychological reasons for enjoying holes. One time, I wrote a Facebook post about the gaps between the escalator stairs leading to the subway at Vokzalna Station, and there was some half-encouraging likes, which really meant my friends liked the post to show they are still my friends.</p>")

Paragraph.create(author_id: jk[:id], story_id: escape[:id], rich_text_str: "<p>The more I looked at the sky that night, the more the astonishment grew within me. The astonishment with our world, with probabilities and improbabilities; with unknown stars; with the stormy night sea, and the lights of a fishing port in the distance; with the unpredictable but surprisingly warm relationships after desperate failures; with mysteries, infinite distances between galaxies, and the laws of nature. Though many people would perhaps find it strange, but back then, I thought about God for the first time. God, the universe, being, nature-names dont matter. I was sitting with a bottle of beer on the top of a clay cliff, listening to sea waves, and thought that the only thing that is impossible in our world is an accident.</p>")
Paragraph.create(author_id: ada[:id], story_id: escape[:id], rich_text_str: "<p>It was getting lighter. I stared into the skies, looking for God there. I even asked It: 'Are You there?' It didnt answer. But when I was about to leave, I noticed that one of the stars right above the horizon blinked. I got up from the bench and slowly went home, smiling.</p>")
Paragraph.create(author_id: jk[:id], story_id: escape[:id], rich_text_str: "<p>I tilted my head back and gazed at the sky. The night was starry, and there were no streetlights around, so I think I could see every little star up there, every subtle offshoot of the Milky Way, every blinking satellite. I made an attempt to imagine the distance between stars, but I failed almost immediately, as I tried to count how many miles are in one light-year. Then, I wondered what were the chances that the energy particles would organize in a way they did to form the universe as we know it today. Perhaps the chances were even lower than if a monkey was expected to write 'War and Peace.' I sipped from the bottle, and tried to calculate the chances of meeting the one for whose return I was waiting for. Among seven billion people living on our planet….</p>")

Paragraph.create(author_id: ada[:id], story_id: battle[:id], rich_text_str: "<p>My reflection stares back at me. The only imperfection is my dark hair, which has the stubborn habit of sticking up, but I manage. I always must appear to the public as the well-groomed prince they know, clean-shaven with round, amber eyes and a strong jaw. My father, King Montgomery of Yiyiroth, made a point of telling me that rather excessively when I was a young boy. Now, at age seventeen, I am expected to appear at the side of my parents on all formal occasions, training for the day I inherit the throne. The obligations that come with being royalty are not typically discussed, which I find infuriating on occasion, especially considering that I am the eldest son of my parents. Tonight, there is yet another dinner and festival that I must attend, thus the reason for my formal attire. Tonight, Yiyiroth celebrates its decade-long three-way alliance between Cidermere and Stairenyth, so it was decided that nobles and royals from those nations would arrive at Castle Yiyiroth to honor the alliance in celebration.</p>")
Paragraph.create(author_id: alan[:id], story_id: battle[:id], rich_text_str: "<p>A servant knocks on my door, asking for permission to come in. I am in my personal quarters, but the servant is one of my valets, and he has likely come to make sure I have everything I require. 'Good evening, Prince Alistair,' says the valet with a slight bow. 'I've been sent to inform you that guests will be arriving soon, and your mother wants you to be there before they arrive.' I adjust my hair for what seems to be the hundredth time as I answer the servant. 'Inform her I shall be downstairs post-haste.' 'Yes, my lord. Do you need any assistance?' he asks. 'No,' I say.</p>")
Paragraph.create(author_id: ada[:id], story_id: battle[:id], rich_text_str: "<p>The valet closes the door as he leaves, and I am left in my own solitude yet again. I am prepared already, all I need to do is walk downstairs and my mother will be content, but I do not wish to just yet. Sitting on my mattress, I count the minutes before my time spent in my chambers is deemed too long. Gatherings such as the one I am about to attend always seem to last an eternity, and this time, the Duke of Cidermere will be there, and he is indeed a man renowned for his ability to talk about nothing yet take up the time of hours. If I am to survive through tonight, I require a moment of rest before.</p>")

## fantasy
Paragraph.create(author_id: alan[:id], story_id: crystal[:id], rich_text_str: "<p>'I'm done with that view. Show me something else,' the King ordered. Dutifully the King's courtiers unfurled a scroll which appeared in back of the large wooden window frame that stood in the middle of the room. 'Not that one. Another!' The courtiers unraveled two more before the King settled on a scene depicting a grove of giant sequoia trees. The King laid back and surveyed the scene. The path between the trees revealed burls on some of the redwoods with wood chips strewn across the dirt path and a sky that was barely visible under the huge branches. In the foreground a squirrel munched on a nut oblivious to the rest of the world. The King had never seen a squirrel before, and it was the fury creature which caught his eye rather than the enormity of the trees.</p>")
Paragraph.create(author_id: bill[:id], story_id: crystal[:id], rich_text_str: "<p>When the King tired of that image, he called for another. Behind the improvised window frame, the courtiers unraveled a painting of the desert. Mesmerized, the King demanded to know 'Who painted this one? Bring him here.'</p>")
Paragraph.create(author_id: alan[:id], story_id: crystal[:id], rich_text_str: "<p>Mohammed, one of the Palace's oldest scene painters, was brought before the King. Motioning with his arm, the King inquired, 'Tell me about this one.' Mohammed took a deep breathe. How does one describe the magic of the desert to one who had never left the Palace, to someone who had only been shown the world through the makeshift window, and had no experience of nature or life beyond the rooms of the Palace.</p>")

Paragraph.create(author_id: bill[:id], story_id: dragon[:id], rich_text_str: "<p>At his birth, the windows of the Palace had been boarded up by the old King and Queen so that the young prince would never be tempted to venture out and would be protected from those who wished him harm, of whom there were many. The King, now in his late twenties, had never set foot over the Palace threshold, never seen his own stables, or felt the wind on his face. He knew nothing of sunshine or mountain lakes. Everything the King had ever seen had been through the images that the Palace painters had put before him.</p>")
Paragraph.create(author_id: george[:id], story_id: dragon[:id], rich_text_str: "<p>Though the King was an intelligent man, understanding the deep mysteries of the desert did not demand intelligence, but something more visceral. Mohammed tried to describe the beauty of the desert as if talking to a blind man, which in some ways is exactly what the King was.</p>")
Paragraph.create(author_id: jk[:id], story_id: dragon[:id], rich_text_str: "<p>'Your majesty, the desert is a magical place with hot sands that can appear pink in a certain light. The wind creates ripples in the sand dunes that can break up the monotony of the endless expanse of land. Blinding gusts of wind will wrap around you like a lover's arms until you lay down and surrender.</p>")

Paragraph.create(author_id: james[:id], story_id: mage[:id], rich_text_str: "<p>People who traverse the desert wear long flowing white robes to reflect the heat from the blistering sun. At times the sand is too hot to walk on, horses would burn their feet if they even tried. There are no roads in the desert, but instead people use camels to transport them and their goods in a long, slow parade. The stars are their only navigation system.</p>")
Paragraph.create(author_id: jk[:id], story_id: mage[:id], rich_text_str: "<p>Despite the protective layers of clothe you wrap around your head, grit will find its way into your mouth, your eyes, and between your teeth. And you will be thirsty my Lord. There is nothing as parched as the lips of a man who is roaming the desert. Optical illusions-called mirages- appear, leading you to water that appear real enough only to evaporate when you arrive at their source. And when you drink the warm water from your canteen it is tinged with the taste of metal that is wet but never refreshing.'</p>")
Paragraph.create(author_id: ada[:id], story_id: mage[:id], rich_text_str: "<p>The King leaned forward intent on learning more about this enchanted place of great beauty and great despair. When Mohammed was finished, the King asked 'If it is as you say, why do men go there?'</p>")

## paranormal
Paragraph.create(author_id: george[:id], story_id: spooky[:id], rich_text_str: "<p>Marty was curled up on the family recliner, staring at the ceiling with his mouth wide open. He had been hearing a dripping noise while he was reading 'All the Kings Men' for a book report, and it was poking at his attention. The book wasnt so enthralling to him anyways. He tried to ignore the sound for a while, but its persistent tune entered into his reading, and the clamor of political speeches and the intrigue contained in the book were colored with the resonance of drips.</p>")
Paragraph.create(author_id: ada[:id], story_id: spooky[:id], rich_text_str: "<p>He shoved the book down on the living room couch, not bothering to mark the page. His father and mother were not at home, both being professors who enjoyed working late in their laboratories at the University of Washington in the department of entomology.</p>")
Paragraph.create(author_id: alan[:id], story_id: spooky[:id], rich_text_str: "<p>By listening inventively, he thought the drips must be landing above him, next to the top of the staircase that leads to his parents bedroom. As he walked towards the dripping sound softly as to not obstruct his hearing, he tried to be alert as possible about the sound of the drips. His intuition was not far off: the drips were landing within the top stair of the staircase. 'But how could something be dripping inside of the stair?' he thought. He couldnt find any logical reason for it.</p>")

Paragraph.create(author_id: jk[:id], story_id: possession[:id], rich_text_str: "<p>Setting my old laptop on a makeshift table made of leftover wood and cardboard, I sat in the cold garage of my shared living house. I lived with nine other people, mostly single guys, in a three-storey house. It was more fun than one could imagine, including the ensuing mess of many bachelors together.</p>")
Paragraph.create(author_id: alan[:id], story_id: possession[:id], rich_text_str: "<p>This late autumn night, I was on Skype with my wife, who was in Ukraine at the time to visit her parents. Since I didnt want to make noise while my roommates slept, I enclosed myself in our unorganized, freezing garage, with two layers of sweaters.</p>")
Paragraph.create(author_id: bill[:id], story_id: possession[:id], rich_text_str: "<p>Anna, my wife, wanted to do a collective meditation session, and I agreed-its not good to disagree with my wife, unless you want trouble. Anyways, we started doing affirmations, saying certain phrases to focus our attention inwards. Slowly, my wife said affirmations for each chakra, our plexuses along our spine that are supposed to have energy. After reaching the crown chakra at the top of the head, or sahasrara, and saying the affirmation for that center, we meditated in silence for awhile.</p>")

Paragraph.create(author_id: ada[:id], story_id: altered[:id], rich_text_str: "<p>I enter my office on the third floor. I always try to say hi to the lackluster face of the cleaning lady who mops the floors. After an automated fingerprint check to enter my office, there is a mandatory shaking of hands with each colleague I meet, if it is a man, as in Ukraine, men and women dont usually shake hands. I sit down at my lunar-moon-shaped wooden desk-the adjoining wall littered with sticky notes to cover holes and clippings of paint. I was instructed by my director to do so.</p>")
Paragraph.create(author_id: bill[:id], story_id: altered[:id], rich_text_str: "<p>Each work day is spontaneous, but somehow expected. Editing technical writing feels this way. I eat lunch with one guy named Zhenya. We are already bored with each other-but feel obliged to eat together since we have been doing so for so long. I leave work like a robot-dazed from information and processing that load.</p>")
Paragraph.create(author_id: james[:id], story_id: altered[:id], rich_text_str: "<p>Today, I saw the homeless lady again as I exited my office. Saw Nikolayav Church again. Saw the church-museum, and the guy who asked me a bunch of questions earlier. I walked by him reluctantly, seeing if he would ignore me. I felt stupid for not going another direction. 'Hey marauder! Hows it going?' the ragged man said. 'You know… got out of work…,' I tried to limit the conversation as much as I could. 'I have an offer for you.'</p>")

## mystery
Paragraph.create(author_id: alan[:id], story_id: hidden[:id], rich_text_str: "<p>It was late at night when I dropped in at a local 24/7 grocery store and bought myself a couple of bottles of cheap beer. Despite being late August, it was still warm outside, though during a recent morning, I noticed hoarfrost on the grass. The summer quickly ran to its end, and though I was an adult, I felt almost like a student who had just realized that there was only one week of summer vacation left. I paid for the beer, chatted with the clerk for a couple of seconds, and left.</p>")
Paragraph.create(author_id: james[:id], story_id: hidden[:id], rich_text_str: "<p>I walked along the empty streets-in our town, no one really hanged out after midnight, at least in the district where I resided; the locals were rather quiet people, and the youth preferred to spend time in the center. Lonesome yellow streetlights smoothly glowed in the dark, filling the air with cozy amber tones, and as I walked, I gradually delved into memories of the previous fall. I remembered changes in my personality, though minute. As my legs stepped on the pavement, my mind broadcasted the visions from the past: falling leaves, first frosts, the smell of smoke in the air, the warmth of her hand in my pocket, an alley in the park. I couldnt remember what we were talking about though, but it didnt matter.</p>")
Paragraph.create(author_id: george[:id], story_id: hidden[:id], rich_text_str: "<p>I found myself standing on the edge of a clay cliff on the outskirts of town. The cliff was rather high-about 50 feet-and its bank was covered with weeds and thistles. A couple of hundred of feet further, the sea was rolling its waves glittering in starlight. I found a low broken bench several steps away from a place where I was standing, sat down, and opened a bottle of beer with my plastic lighter. One of the most useful skills I ever learned.</p>")

Paragraph.create(author_id: jk[:id], story_id: bargain[:id], rich_text_str: "<p>Mary was alone again on a Saturday. Her father, Harold was on another business trip to Mississippi, and the house was all to herself, which meant she could have pasta every day if she wanted. Her medicine for lowering her testosterone levels made her gain weight, and her father was not keen on her pasta indulgence.</p>")
Paragraph.create(author_id: james[:id], story_id: bargain[:id], rich_text_str: "<p>I can add tuna too. Some mozzarella. It was so quiet in the house, her thoughts sounded like they were being spoken out loud. In the town of Woodway, Washington, theres not much to hear besides birdsong and the rumble of an occasional car.</p>")
Paragraph.create(author_id: ada[:id], story_id: bargain[:id], rich_text_str: "<p>Mary peeled back her fluffy blanket and stiffly walked to the kitchen. She connected her iPhone to the old karaoke speaker no one used for karaoke and put on Cardi B. A 808 beat reverberated off the high living room ceiling. Cardis rhymes and ghetto style among blue jay calls.</p>")

Paragraph.create(author_id: bill[:id], story_id: choices[:id], rich_text_str: "<p>Smeared blood, shredded feathers. Clearly, the bird was dead. But wait, the slight fluctuation of its chest, the slow blinking of its shiny black eyes. No, it was alive. I had been typing an English essay when I heard my cat's loud meows and the flutter of wings. I had turned slightly at the noise and had found the barely breathing bird in front of me.</p>")
Paragraph.create(author_id: alan[:id], story_id: choices[:id], rich_text_str: "<p>The shock came first. Mind racing, heart beating faster, blood draining from my face. I instinctively reached out my hand to hold it, like a long-lost keepsake from my youth. But then I remembered that birds had life, flesh, blood. Death. Dare I say it out loud? Here, in my own home?</p>")
Paragraph.create(author_id: george[:id], story_id: choices[:id], rich_text_str:  "<p>Within seconds, my reflexes kicked in. Get over the shock. Gloves, napkins, towels. Band-aid? How does one heal a bird? I rummaged through the house, keeping a wary eye on my cat. Donning yellow rubber gloves, I tentatively picked up the bird. Never mind the cat's hissing and protesting scratches, you need to save the bird. You need to ease its pain.</p>")

## horror
Paragraph.create(author_id: george[:id], story_id: blood[:id], rich_text_str: "<p>He kept close to his uncle as they weaved between huge round tables draped with white cloth. They were like giant versions of the mints Adejo's uncle had in the van, only they were speckled with stains both dark and pale. A middle-aged woman watched him with one diseased looking eye as he passed, as a younger man kissed her hard while sharing her chair. An old man stirred a thin, plastic stick around his tall glass while examining something at the bottom of it. He passed another table, where a girl his own age sat alone looking at something on either a huge phone or a tiny TV she held in her hands, the images from the screen painting her face an ever-changing palette of muted colours. Adejo tried to sneak a peek, but his uncle grabbed his arm and dragged him on before he had the chance.</p>")
Paragraph.create(author_id: alan[:id], story_id: blood[:id], rich_text_str: "<p>The kitchen was as bright as the big room was dark, a blaze of quivering florescent lights and shiny metal surfaces. A thin man with the dishevelled appearance of an artist wore a food splattered apron as he wiped the surfaces with a cloth, creating smeary waves that adorned everything he touched. Adejo's uncle asked the thin man something, and he pointed them deeper into the kitchen.</p>")
Paragraph.create(author_id: bill[:id], story_id: blood[:id], rich_text_str: "<p>The air felt sticky, like it had been bundled up, fried in oil, and then released back into the atmosphere. They hadn't gone far when Adejo's uncle reached a huddle of black bags at the back of the room. He lifted one and thrust it unceremoniously in Adejo's direction. It was bulging and heavy, and it almost dragged Adejo down to the floor, but he managed to wrestle it back up with sufficient manly qualities that he hoped would impress his uncle on what was his first night at work. Adejo was keen to prove his worth. He didn't want these first impressions to be clouded by sympathy. With Adejo wrestling one black bag his uncle effortlessly carried the other three, before two men on the dance floor (the fat man and his emaciated sidekick), blocked his path, the skinny one snatching a bag from his uncle's grip that he was now swinging around like he and the bag were old lovers.</p>")

Paragraph.create(author_id: ada[:id], story_id: creepy[:id], rich_text_str: "<p>Adejo slunk into the seat that the kissing couple had vacated. Numerous drinks had been abandoned on the table, and with no obvious claims of ownership in the vicinity Adejo was tempted to take a furtive sip from the glass nearest to him. He suddenly felt overwhelmed by thirst, whether from the suffocating heat in the room or the sickly kitchen smells now lodged in his throat. But just then Adejo was distracted by the sight of his uncle managing to break free of the commotion, and after a mildly aggressive game of tug-of-war with the bag dancer, his uncle persuaded him to relinquish his dancing partner. Adejo couldn't hear what was being said, but suddenly the bag dancer was shouting while trying not to fall over, and the fat man - who only a second ago had been hugging Adejo's uncle - was now jabbing a finger at him, his face all rashy and sweaty. But at least his uncle had the bag back, and was now moving away from the dance floor, a quick glance at Adejo confirming his own suspicions that now was probably a good time for him to move too.</p>")
Paragraph.create(author_id: jk[:id], story_id: creepy[:id], rich_text_str: "<p>There was a risk that the same shiny floors they were now navigating in the opposite direction would scupper Adejo's delicate balancing act, his hands carefully cradling the hidden glass pressed against his skin beneath his jumper. He tried to keep pace with his uncle who marched in front of him, dragging the black bags around one of the pillars before the glass doors miraculously separated upon some unseen command.</p>")
Paragraph.create(author_id: james[:id], story_id: creepy[:id], rich_text_str: "<p>Adejo had never heard his uncle curse. What made it worse was that he cursed in Hausa. And what made it worse again was that he struck his fist off the back of the van. Adejo thought his uncle might swear again, and follow up by striking him instead of the hard metallic surface of the vehicle, an act Adjeo thought would be appropriate to the sense of guilt he was feeling.</p>")

Paragraph.create(author_id: alan[:id], story_id: demon[:id], rich_text_str: "<p>He'd only known his Uncle Kayin two weeks, but sensed that a man who turned the radio up full blast to sing-a-long to a song he liked ('A great way to learn English Adejo!' he had shouted on the drive down) wasn't usually prone to acts of violence, let alone repeated acts. At least Adejo hoped not. After all, this was 'The Great Example' Adejo's mother had spoken of with such adoration. Yet now the legend seemed diminished in the flesh, reality rendering his uncle fallible no matter how glorious the reputation preceding him. The status of being known as 'The Great Example' had even overshadowed his first name, Uncle Kayin. In fact, it was only when Adejo learned that he was to follow in his uncle's footsteps that he heard the real name of his mother's brother, the living proof that the journey could not only be endured, but that it could end in glory.</p>")
Paragraph.create(author_id: ada[:id], story_id: demon[:id], rich_text_str: "<p>With his uncle gone Adejo sat sucking the last mint in the passenger seat of the van as instructed (it was the least he could do), debating where he could get rid of the glass that he could see now had the filter of a smoked cigarette floating in it. He'd drunk worse - much worse - but now his curiosity about the golden liquid buoying the butt no longer held any appeal, and any thirst he'd used to justify taking the glass in the first place was being eased by the mint, a thirst that he had no right to indulge in the first place. Adejo was disgusted with himself that he'd disappointed his uncle, and surely blown any chance he ever had of accompanying him on another job. His uncle had even bestowed a level of responsibility on him that he was surely expected to uphold, a pact of trust that Adejo had betrayed in an instant by leaving the bag behind.</p>")
Paragraph.create(author_id: alan[:id], story_id: demon[:id], rich_text_str: "<p>The beer swirled round and round in the glass, Adejo increasing the pace until the surface level of the liquid repeatedly broke over the butt, drowning it again and again. Each time it tried to fight its way back up Adejo realised just how helpless their plight must have been that night, their solitary boat alone in the dark while nature or God or fate or bad luck toyed with their lives, dragging them under, then letting them rise again, dragging them under, then letting them rise again, with the roof of each new wave collapsing on their heads until the roar of the water had silenced the screams of the dying.</p>")

## romance
Paragraph.create(author_id: jk[:id], story_id: forbidden[:id], rich_text_str: "<p>Shortly after my education at college was finished, I happened to be staying at Paris with an English friend. We were both young men then, and lived, I am afraid, rather a wild life, in the delightful city of our sojourn. One night, we were idling about the neighborhood of the Palais Royal, doubtful to what amusement we should next betake ourselves. My friend proposed a visit to Frascatis-but his suggestion was not to my taste. I knew Frascatis, as the French saying is, by heart; had lost and won plenty of five-franc pieces there, merely for amusements sake, until it was amusement no longer, and was thoroughly tired of all the ghastly respectabilities of such a social anomaly as a respectable gambling-house.</p>")
Paragraph.create(author_id: george[:id], story_id: forbidden[:id], rich_text_str: "<p>'For Heavens sake,' said I to my friend, 'let us go somewhere where we can see a little genuine, blackguard, poverty-stricken gaming with no false gingerbread glitter thrown over it all. Let us get away from fashionable Frascatis to a house where they dont mind letting in a man with a ragged coat, or a man with no coat, ragged or otherwise.'</p>")
Paragraph.create(author_id: james[:id], story_id: forbidden[:id], rich_text_str: "<p>In another minute, we arrived at the door, and entered the house, the back of which you have drawn in your sketch. When we got upstairs, and had left our hats and sticks with the doorkeeper, we were admitted into the chief gambling-room. We did not find many people assembled there. But, few as the men were who looked up at us on our entrance, they were all types-lamentably true types-of their respective classes.</p>")

Paragraph.create(author_id: bill[:id], story_id: timing[:id], rich_text_str: "<p>It was another early sunset on a rainy day in Seattle. Andrew was walking with a paper bag of groceries back to his downtown studio apartment. He had gotten government permission to stay in this apartment as part of the Upbeat program, focusing on bettering drug-affected neighborhoods in King County. It was an artist supplement program, and Andrew was a published haiku poet and teacher of haiku in public education and sometimes colleges.</p>")
Paragraph.create(author_id: ada[:id], story_id: timing[:id], rich_text_str: "<p>Like a true Seattleite, he had no umbrella today-just a polyester jacket to wade off the rain. He was gripping his paper grocery bag with a regret that he tried to be so environmentally friendly, as his groceries seemed to be slipping away from him, slowly being soaked. Nearing the King County courthouse, he saw a young woman in the distance, shivering. She was sitting on the courtyard grass, despondently staring down, wearing a hoodie. There was a cardboard sign on her left that read, 'Anything will help.'</p>")
Paragraph.create(author_id: alan[:id], story_id: timing[:id], rich_text_str: "<p>Thoughts began to run through Andrews mind. Where is she going to sleep? Isnt she going to get hypothermia? Is she sick, because she is not even holding up her sign, or is she just depressed? But as he came a few feet from her, his thoughts calmed down and he simply had a feeling of wanting to help her in some way.</p>")

Paragraph.create(author_id: ada[:id], story_id: gentleman[:id], rich_text_str: "<p>Jason glanced at his watch and his heart started to beat twice as fast-he was late. He accelerated his pace, but there still were two blocks to run. The weather was hot and sunny-his hopes to arrive to the meeting place neat and classy were now a fragment of imagination. At the moment, what he cared about was getting there on time. When he finally saw the sign of the Starbucks café where the meeting had been arranged, he still had one minute in reserve to wash his face and to fetch his breath. He wanted to finish his period of singleness, and Shannon, the girl he was going out on a date today, was a rather promising candidate.</p>")
Paragraph.create(author_id: bill[:id], story_id: gentleman[:id], rich_text_str: "<p>Shannon was sitting at the backseat of a retro-looking cab, thinking about the date and the guy she agreed to go out with. When she was chatting with him on the Web, he seemed to be intelligent-such a nice contrast after all her yuppie acquaintances thinking only about their careers and appearance. She had no serious plans for Jason though-at least, for now. She only wanted was to drown her loneliness after breaking up with her recent boyfriend; she hoped new people would cheer her up. And who knows-maybe this blind date would result into something bigger.</p>")
Paragraph.create(author_id: ada[:id], story_id: gentleman[:id], rich_text_str: "<p>When Shannon finally showed herself, Jason already drank two cups of coffee. He recognized her immediately, even though they never exchanged photos or talked on Skype. Somehow, she recognized him too, and smiled at him. Jason was astonished-she looked stunning, even though she was dressed up quite simple. She seemed independent and unobstructed, and he liked it. 'She seems to live a happy life,' he thought.</p>")

## other
Paragraph.create(author_id: james[:id], story_id: lilac[:id], rich_text_str: "<p>Jason glanced at his watch and his heart started to beat twice as fast-he was late. He accelerated his pace, but there still were two blocks to run. The weather was hot and sunny-his hopes to arrive to the meeting place neat and classy were now a fragment of imagination. At the moment, what he cared about was getting there on time. When he finally saw the sign of the Starbucks café where the meeting had been arranged, he still had one minute in reserve to wash his face and to fetch his breath. He wanted to finish his period of singleness, and Shannon, the girl he was going out on a date today, was a rather promising candidate.</p>")
Paragraph.create(author_id: alan[:id], story_id: lilac[:id], rich_text_str: "<p>Shannon was sitting at the backseat of a retro-looking cab, thinking about the date and the guy she agreed to go out with. When she was chatting with him on the Web, he seemed to be intelligent-such a nice contrast after all her yuppie acquaintances thinking only about their careers and appearance. She had no serious plans for Jason though-at least, for now. She only wanted was to drown her loneliness after breaking up with her recent boyfriend; she hoped new people would cheer her up. And who knows-maybe this blind date would result into something bigger.</p>")
Paragraph.create(author_id: james[:id], story_id: lilac[:id], rich_text_str: "<p>When Shannon finally showed herself, Jason already drank two cups of coffee. He recognized her immediately, even though they never exchanged photos or talked on Skype. Somehow, she recognized him too, and smiled at him. Jason was astonished-she looked stunning, even though she was dressed up quite simple. She seemed independent and unobstructed, and he liked it. 'She seems to live a happy life,' he thought.</p>")

Paragraph.create(author_id: george[:id], story_id: how_to[:id], rich_text_str: "<p>After the formal greetings and a minute of embarrassing silence that almost always appears between people who dont know each other well enough, they finally felt more free and started to talk in earnest. Live communication was so different from what they got used to on the Internet. Gestures, tone of voice-hundreds of minor details that affect our perception of people. Jason discovered she was not as sweet and diverse of a person as she seemed on online. She judged her yuppie friends and their life priorities fiercely, and it was rather unpleasant. Jason tried to change the topic several times, but Shannon would just stop talking in confusion as if she knew nothing else of worth to be discussed.</p>")
Paragraph.create(author_id: ada[:id], story_id: how_to[:id], rich_text_str: "<p>Shannon felt a bit irritated at Jason. When they were communicating online, he seemed to be so caring about her interests, about her problems and priorities. He would supply precise and brief psychological characteristics of her yuppie friends based solely on Shannons descriptions, and give her reasonable advice. However, now he didnt seem to be so interested in what she was talking about, and tried to speak about something else, about things that were so much less important to her-art, literature, cinema. Shannon thought such topics were suitable only for romantic teenage couples, but she was a modern woman, and she didnt want to waste time on anything she saw as unimportant.</p>")
Paragraph.create(author_id: alan[:id], story_id: how_to[:id], rich_text_str: "<p>This is where things started to get interesting.</p>")

Paragraph.create(author_id: james[:id], story_id: family[:id], rich_text_str: "<p>The fat man had his arm around Adejo's uncle's neck like they were old friends, every now and then pulling him closer when there was some particular part of the song he felt he needed to share more intimately, singing into his uncle's ear and making him smile in a way that looked painful.</p>")
Paragraph.create(author_id: jk[:id], story_id: family[:id], rich_text_str: "<p>Whoever the fat man was - and Adejo couldn't imagine his uncle ever being friends with a white person - he seemed to be the only one who knew the words of the song (that Adejo thought might be Irish, but then he hadn't heard Irish before, at least he didn't think so), blasting out the lyrics with a viciousness that made him look like he wished he had something to kick while he was singing.</p>")
Paragraph.create(author_id: george[:id], story_id: family[:id], rich_text_str: "<p>Adejo still wasn't quite sure how his uncle had got caught up with the two wedding guests in the first place. He had never been to a wedding before and had been excited until his uncle made it clear that they weren't really going to the wedding. 'We're just going to the kitchen, to pick up the bags. We won't even see the wedding. I'm sorry Adejo. You'll hear it though. I can promise you that.' For a while it seemed that they wouldn't even hear the wedding, let alone see it, because when his uncle parked the van and went to the steel door that led to the kitchen it wouldn't open, no matter how many times his uncle tried pressing different numbers into the pad on the wall.</p>")


puts "Seeding complete! :)"